-- LinuxDex Database Schema
-- Run this in your Supabase SQL editor

-- Create the profiles table
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    public_profile BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Create the distro_history table
CREATE TABLE IF NOT EXISTS public.distro_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    distro_name TEXT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE,
    current_flag BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable Row Level Security
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.distro_history ENABLE ROW LEVEL SECURITY;

-- Create policies for RLS
-- Profiles policies
CREATE POLICY "Users can view their own profile" ON public.profiles
    FOR SELECT USING (auth.uid() = id);

CREATE POLICY "Users can insert their own profile" ON public.profiles
    FOR INSERT WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can update their own profile" ON public.profiles
    FOR UPDATE USING (auth.uid() = id) WITH CHECK (auth.uid() = id);

-- Public can view profiles if public_profile is true
CREATE POLICY "Public can view public profiles" ON public.profiles
    FOR SELECT USING (public_profile = true);

-- Users can only see their own distro history
CREATE POLICY "Users can view their own distro history" ON public.distro_history
    FOR SELECT USING (auth.uid() = user_id);

-- Users can insert their own distro history
CREATE POLICY "Users can insert their own distro history" ON public.distro_history
    FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Users can update their own distro history
CREATE POLICY "Users can update their own distro history" ON public.distro_history
    FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- Users can delete their own distro history
CREATE POLICY "Users can delete their own distro history" ON public.distro_history
    FOR DELETE USING (auth.uid() = user_id);

-- Create unique constraint to prevent duplicates
ALTER TABLE public.distro_history ADD CONSTRAINT unique_user_distro_start UNIQUE (user_id, distro_name, start_date);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_distro_history_user_id ON public.distro_history(user_id);
CREATE INDEX IF NOT EXISTS idx_distro_history_current_flag ON public.distro_history(current_flag);

-- Create function to update updated_at timestamp
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = TIMEZONE('utc'::text, NOW());
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger to automatically update updated_at
CREATE TRIGGER handle_profiles_updated_at
    BEFORE UPDATE ON public.profiles
    FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

CREATE TRIGGER handle_distro_history_updated_at
    BEFORE UPDATE ON public.distro_history
    FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();